---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  name: openebs
  namespace: openebs
  labels:
    kubeaddons.mesosphere.io/name: openebs
    kubeaddons.mesosphere.io/provides: storageclass
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.7.0-1"
    appversion.kubeaddons.mesosphere.io/awsebscsiprovisioner: "1.7.0"
    values.chart.helm.kubeaddons.mesosphere.io/openebs: "https://murat.karslioglu.com/charts/stable/openebs/values.yaml"
spec:
  namespace: kube-system
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: defaultstorageclass-protection
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true 
  chartReference:
    chart: stable/openebs
    version: 1.7.0
# Optional values
#    values: |
#      ---
#      defaultStorageConfig:
#        enabled: true
#      analytics:
#        enabled: true
# Specify in hours the duration after which a ping event needs to be sent.
#        pingInterval: "24h"
